batch_size: 10000            # track segments
event_batch_size: 2          # tpcs
write_batch_size: 1000       # batches
is_spill_sim: 0              # boolean
if_active_volume_check: 0    # boolean
spill_period: 1.2e6          # microseconds
event_separator: 'eventID'   # 'eventID'
tracks_dset_name: 'segments' # or 'segments'
max_events_per_file: 1000
pdg_to_recombination_model: # Box 1; Birks 2; NEST_ER 3; NEST_ALPHA 4; NEST_NR 5
    11: 3 # electron
    13: 2 # muon
    2212: 2 # proton
    321: 2 # kaon
    211: 2 # pion
    1000020040: 4 # alpha
    1000180400: 5 # 40Ar
    1000010020: 2 # deuteron
er_energy_threshold: 1.0 # MeV
default_recombination_model: 2 # 1 or 2